### ISSUE TITLE
Testes deixando lixo no banco

### ISSUE THREAD

**Issue by toledompm** [NicolasFujisawa/fatec-lab-dev-5#28]
Quando um teste de integração falha, todas alterações feitas no banco até o ponto de falha são persistidos.

Precisamos configurar um "tear down", pra desfazer tudo quando o teste terminar *ou* falhar.

**Comment by toledompm** [comment]
Rodar testes local passando active profile:
``` bash
SPRING_PROFILES_ACTIVE=test gradle test
```

**Comment by NicolasFujisawa** [comment]
Tentei usar a anotação @ActiveProfiles nos testes mas não funcionou, sobre testes local eu não tive problemas com o Intellij (clicando no test) mas em container acho que a solução seria essa mesmo https://github.com/NicolasFujisawa/fatec-lab-dev-5/issues/28#issuecomment-787482282

**Comment by NicolasFujisawa** [comment]
Caraca, marquei um cara sem querer
