### ISSUE TITLE
Adicionar h2 database para testes de integração

### ISSUE THREAD

**Issue by NicolasFujisawa** [NicolasFujisawa/fatec-lab-dev-5#7]
usar dependência h2 e configurar o ambiente application.yml na pasta test

**Comment by jasondavindev** [comment]
Acho pouco interessante. O correto seria mockar a parte que conversa com o banco

**Comment by toledompm** [comment]
Eu acho válido alguns testes e2e inserirem registros no banco, não sei se vale a pena implementar agora já, mas se o app crescer vai ser útil

**Comment by NicolasFujisawa** [comment]
Coloquei pqe talvez o mineda deixe como obrigatório, tem uns exemplos de testes que ele usa o banco nas aulas dele, h2 é pra não popular o nosso banco com testes.
